Package.describe({
  summary: "Flat Web User Interface Kit"
});

Package.on_use(function (api) {


  api.add_files([
    // FILES
    'assets/js/jquery-1.8.3.min.js',
    'assets/js/jquery-ui-1.10.3.custom.min.js',
    'assets/images/login/imac-2x.png',
    'assets/js/bootstrap-select.js',
    'assets/js/bootstrap-switch.js',
    'assets/js/jquery.ui.touch-punch.min.js',
    'assets/js/flatui-radio.js',
    'assets/js/application.js',
    'assets/js/jquery.placeholder.js',
    'assets/js/icon-font-ie7.js',
    'assets/js/flatui-checkbox.js',
    'assets/js/jquery.stacktable.js',
    'assets/js/html5shiv.js',
    'assets/js/jquery.tagsinput.js',
    'assets/fonts/Flat-UI-Icons.woff',
    'assets/fonts/Flat-UI-Icons.ttf',
    'assets/fonts/Flat-UI-Icons.eot',
    'assets/fonts/Flat-UI-Icons.dev.svg',
    'assets/fonts/Flat-UI-Icons.svg',
    'assets/fonts/icomoon-session.json',
    'assets/images/icons/Clipboard@2x.png',
    'assets/images/icons/Pocket@2x.png',
    'assets/images/icons/Infinity-Loop@2x.png',
    'assets/images/icons/Watches@2x.png',
    'assets/images/icons/Pensils@2x.png',
    'assets/images/icons/Book@2x.png',
    'assets/images/icons/Map@2x.png',
    'assets/images/icons/Mail@2x.png',
    'assets/images/icons/Retina-Ready@2x.png',
    'assets/images/icons/Gift-Box@2x.png',
    'assets/images/icons/Calendar@2x.png',
    'assets/images/icons/Toilet-Paper@2x.png',
    'assets/images/icons/Compas@2x.png',
    'assets/images/icons/Chat@2x.png',
    'assets/images/todo/done-2x.png',
    'assets/images/todo/search-2x.png',
    'assets/images/todo/todo.png',
    'assets/images/todo/todo-2x.png',
    'assets/images/todo/search.png',
    'assets/images/todo/done.png',
    'assets/images/switch/mask-square.png',
    'assets/images/switch/mask.png',
    'assets/images/tile/ribbon-2x.png',
    'assets/images/tile/ribbon.png',
    'assets/images/login/imac.png',
    'assets/js/bootstrap.min.js',
    'assets/images/login/icon.png',
    'assets/images/video/volume-full-2x.png',
    'assets/images/video/play.png',
    'assets/images/video/volume-full.png',
    'assets/images/video/poster.jpg',
    'assets/images/video/pause.png',
    'assets/images/video/volume-off.png',
    'assets/images/video/play-2x.png',
    'assets/images/video/pause-2x.png',
    'assets/images/video/volume-off-2x.png',
    'assets/images/video/fullscreen-2x.png',
    'assets/images/video/fullscreen.png',
    'assets/css/flat-ui.css',
    'assets/css/flat-ui-icons-reset.css',
    'assets/css/bootstrap.css'
    // END FILES
  ], 'client');
});